// Autogenerated with StateSmith 0.17.2+a7141c241054b3177bab267557ecb45a8dcedd67.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#nullable enable

namespace FinancialTracker.StateMachines
{
    // Generated state machine
    public partial class ServerStateMachine
    {
        public enum EventId
        {
            CANCELSENDING = 0,
            CLIENTCONNECTED = 1,
            CLIENTDISCONNECTED = 2,
            FINISHEDSENDING = 3,
            SEND = 4,
            START = 5,
            STOP = 6,
        }

        public const int EventIdCount = 7;

        public enum StateId
        {
            ROOT = 0,
            IDLE = 1,
            RUNNING = 2,
            CONNECTED = 3,
            IDLECONNECTED = 4,
            SENDING = 5,
            NOTCONNECTED = 6,
        }

        public const int StateIdCount = 7;

        // Used internally by state machine. Feel free to inspect, but don't modify.
        public StateId stateId;

        // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
        public ServerStateMachine()
        {
        }

        // Starts the state machine. Must be called before dispatching events. Not thread safe.
        public void Start()
        {
            ROOT_enter();
            // ROOT behavior
            // uml: TransitionTo(ROOT.<InitialState>)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
                // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.

                // ROOT.<InitialState> behavior
                // uml: TransitionTo(Idle)
                {
                    // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `Idle`.
                    IDLE_enter();

                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for ROOT.<InitialState>
            } // end of behavior for ROOT
        }

        // Dispatches an event to the state machine. Not thread safe.
        // Note! This function assumes that the `eventId` parameter is valid.
        public void DispatchEvent(EventId eventId)
        {
            switch (this.stateId)
            {
                // STATE: ServerStateMachine
                case StateId.ROOT:
                    // No events handled by this state (or its ancestors).
                    break;

                // STATE: Idle
                case StateId.IDLE:
                    switch (eventId)
                    {
                        case EventId.START: IDLE_start(); break;
                    }
                    break;

                // STATE: Running
                case StateId.RUNNING:
                    switch (eventId)
                    {
                        case EventId.STOP: RUNNING_stop(); break;
                    }
                    break;

                // STATE: Connected
                case StateId.CONNECTED:
                    switch (eventId)
                    {
                        case EventId.CLIENTDISCONNECTED: CONNECTED_clientdisconnected(); break;
                        case EventId.STOP: RUNNING_stop(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: IdleConnected
                case StateId.IDLECONNECTED:
                    switch (eventId)
                    {
                        case EventId.SEND: IDLECONNECTED_send(); break;
                        case EventId.STOP: RUNNING_stop(); break; // First ancestor handler for this event
                        case EventId.CLIENTDISCONNECTED: CONNECTED_clientdisconnected(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: Sending
                case StateId.SENDING:
                    switch (eventId)
                    {
                        case EventId.FINISHEDSENDING: SENDING_finishedsending(); break;
                        case EventId.CANCELSENDING: SENDING_cancelsending(); break;
                        case EventId.STOP: RUNNING_stop(); break; // First ancestor handler for this event
                        case EventId.CLIENTDISCONNECTED: CONNECTED_clientdisconnected(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: NotConnected
                case StateId.NOTCONNECTED:
                    switch (eventId)
                    {
                        case EventId.CLIENTCONNECTED: NOTCONNECTED_clientconnected(); break;
                        case EventId.STOP: RUNNING_stop(); break; // First ancestor handler for this event
                    }
                    break;
            }

        }

        // This function is used when StateSmith doesn't know what the active leaf state is at
        // compile time due to sub states or when multiple states need to be exited.
        private void ExitUpToStateHandler(StateId desiredState)
        {
            while (this.stateId != desiredState)
            {
                switch (this.stateId)
                {
                    case StateId.IDLE: IDLE_exit(); break;

                    case StateId.RUNNING: RUNNING_exit(); break;

                    case StateId.CONNECTED: CONNECTED_exit(); break;

                    case StateId.IDLECONNECTED: IDLECONNECTED_exit(); break;

                    case StateId.SENDING: SENDING_exit(); break;

                    case StateId.NOTCONNECTED: NOTCONNECTED_exit(); break;

                    default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
                }
            }
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ROOT
        ////////////////////////////////////////////////////////////////////////////////

        private void ROOT_enter()
        {
            this.stateId = StateId.ROOT;
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state IDLE
        ////////////////////////////////////////////////////////////////////////////////

        private void IDLE_enter()
        {
            this.stateId = StateId.IDLE;
        }

        private void IDLE_exit()
        {
            this.stateId = StateId.ROOT;
        }

        private void IDLE_start()
        {
            // Idle behavior
            // uml: Start / { OnStart(); } TransitionTo(Running)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                IDLE_exit();

                // Step 2: Transition action: `OnStart();`.
                OnStart();

                // Step 3: Enter/move towards transition target `Running`.
                RUNNING_enter();

                // Running.<InitialState> behavior
                // uml: TransitionTo(NotConnected)
                {
                    // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `NotConnected`.
                    NOTCONNECTED_enter();

                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for Running.<InitialState>
            } // end of behavior for Idle

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state RUNNING
        ////////////////////////////////////////////////////////////////////////////////

        private void RUNNING_enter()
        {
            this.stateId = StateId.RUNNING;
        }

        private void RUNNING_exit()
        {
            this.stateId = StateId.ROOT;
        }

        private void RUNNING_stop()
        {
            // Running behavior
            // uml: Stop / { OnStop(); } TransitionTo(Idle)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: `OnStop();`.
                OnStop();

                // Step 3: Enter/move towards transition target `Idle`.
                IDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Running

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state CONNECTED
        ////////////////////////////////////////////////////////////////////////////////

        private void CONNECTED_enter()
        {
            this.stateId = StateId.CONNECTED;
        }

        private void CONNECTED_exit()
        {
            this.stateId = StateId.RUNNING;
        }

        private void CONNECTED_clientdisconnected()
        {
            // Connected behavior
            // uml: ClientDisconnected TransitionTo(NotConnected)
            {
                // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.RUNNING);

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `NotConnected`.
                NOTCONNECTED_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Connected

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state IDLECONNECTED
        ////////////////////////////////////////////////////////////////////////////////

        private void IDLECONNECTED_enter()
        {
            this.stateId = StateId.IDLECONNECTED;
        }

        private void IDLECONNECTED_exit()
        {
            this.stateId = StateId.CONNECTED;
        }

        private void IDLECONNECTED_send()
        {
            // IdleConnected behavior
            // uml: Send TransitionTo(Sending)
            {
                // Step 1: Exit states until we reach `Connected` state (Least Common Ancestor for transition).
                IDLECONNECTED_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Sending`.
                SENDING_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for IdleConnected

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state SENDING
        ////////////////////////////////////////////////////////////////////////////////

        private void SENDING_enter()
        {
            this.stateId = StateId.SENDING;
        }

        private void SENDING_exit()
        {
            this.stateId = StateId.CONNECTED;
        }

        private void SENDING_cancelsending()
        {
            // Sending behavior
            // uml: CancelSending TransitionTo(IdleConnected)
            {
                // Step 1: Exit states until we reach `Connected` state (Least Common Ancestor for transition).
                SENDING_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IdleConnected`.
                IDLECONNECTED_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Sending

            // No ancestor handles this event.
        }

        private void SENDING_finishedsending()
        {
            // Sending behavior
            // uml: FinishedSending TransitionTo(IdleConnected)
            {
                // Step 1: Exit states until we reach `Connected` state (Least Common Ancestor for transition).
                SENDING_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IdleConnected`.
                IDLECONNECTED_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Sending

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state NOTCONNECTED
        ////////////////////////////////////////////////////////////////////////////////

        private void NOTCONNECTED_enter()
        {
            this.stateId = StateId.NOTCONNECTED;
        }

        private void NOTCONNECTED_exit()
        {
            this.stateId = StateId.RUNNING;
        }

        private void NOTCONNECTED_clientconnected()
        {
            // NotConnected behavior
            // uml: ClientConnected TransitionTo(Connected)
            {
                // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
                NOTCONNECTED_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Connected`.
                CONNECTED_enter();

                // Connected.<InitialState> behavior
                // uml: TransitionTo(IdleConnected)
                {
                    // Step 1: Exit states until we reach `Connected` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `IdleConnected`.
                    IDLECONNECTED_enter();

                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for Connected.<InitialState>
            } // end of behavior for NotConnected

            // No ancestor handles this event.
        }

        // Thread safe.
        public static string StateIdToString(StateId id)
        {
            switch (id)
            {
                case StateId.ROOT: return "ROOT";
                case StateId.IDLE: return "IDLE";
                case StateId.RUNNING: return "RUNNING";
                case StateId.CONNECTED: return "CONNECTED";
                case StateId.IDLECONNECTED: return "IDLECONNECTED";
                case StateId.SENDING: return "SENDING";
                case StateId.NOTCONNECTED: return "NOTCONNECTED";
                default: return "?";
            }
        }

        // Thread safe.
        public static string EventIdToString(EventId id)
        {
            switch (id)
            {
                case EventId.CANCELSENDING: return "CANCELSENDING";
                case EventId.CLIENTCONNECTED: return "CLIENTCONNECTED";
                case EventId.CLIENTDISCONNECTED: return "CLIENTDISCONNECTED";
                case EventId.FINISHEDSENDING: return "FINISHEDSENDING";
                case EventId.SEND: return "SEND";
                case EventId.START: return "START";
                case EventId.STOP: return "STOP";
                default: return "?";
            }
        }
    }
}
