// Autogenerated with StateSmith 0.17.2+a7141c241054b3177bab267557ecb45a8dcedd67.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#nullable enable

using CommunityToolkit.Mvvm.ComponentModel;

namespace FinancialTracker.StateMachines
{
    // Generated state machine
    public partial class SyncServer : ObservableObject
    {
        public enum EventId
        {
            CONNECT = 0,
            CONNECTED = 1,
            CONNECTIONFAILED = 2,
            DISCONNECT = 3,
            FINISHEDSENDING = 4,
            SEND = 5,
        }

        public const int EventIdCount = 6;

        public enum StateId
        {
            ROOT = 0,
            CONNECTED = 1,
            CONNECTEDIDLE = 2,
            SENDING = 3,
            CONNECTING = 4,
            DISCONNECTED = 5,
        }

        public const int StateIdCount = 6;

        // Used internally by state machine. Feel free to inspect, but don't modify.
        [ObservableProperty]
        public partial StateId CurrentStateId { get; set; }

        // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
        public SyncServer()
        {
        }

        // Starts the state machine. Must be called before dispatching events. Not thread safe.
        public void Start()
        {
            ROOT_enter();
            // ROOT behavior
            // uml: TransitionTo(ROOT.<InitialState>)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
                // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.

                // ROOT.<InitialState> behavior
                // uml: TransitionTo(Disconnected)
                {
                    // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `Disconnected`.
                    DISCONNECTED_enter();

                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for ROOT.<InitialState>
            } // end of behavior for ROOT
        }

        // Dispatches an event to the state machine. Not thread safe.
        // Note! This function assumes that the `eventId` parameter is valid.
        public void DispatchEvent(EventId eventId)
        {
            switch (this.CurrentStateId)
            {
                // STATE: SyncServer
                case StateId.ROOT:
                    // No events handled by this state (or its ancestors).
                    break;

                // STATE: Connected
                case StateId.CONNECTED:
                    switch (eventId)
                    {
                        case EventId.DISCONNECT: CONNECTED_disconnect(); break;
                    }
                    break;

                // STATE: ConnectedIdle
                case StateId.CONNECTEDIDLE:
                    switch (eventId)
                    {
                        case EventId.SEND: CONNECTEDIDLE_send(); break;
                        case EventId.DISCONNECT: CONNECTED_disconnect(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: Sending
                case StateId.SENDING:
                    switch (eventId)
                    {
                        case EventId.FINISHEDSENDING: SENDING_finishedsending(); break;
                        case EventId.DISCONNECT: CONNECTED_disconnect(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: Connecting
                case StateId.CONNECTING:
                    switch (eventId)
                    {
                        case EventId.CONNECTED: CONNECTING_connected(); break;
                        case EventId.CONNECTIONFAILED: CONNECTING_connectionfailed(); break;
                    }
                    break;

                // STATE: Disconnected
                case StateId.DISCONNECTED:
                    switch (eventId)
                    {
                        case EventId.CONNECT: DISCONNECTED_connect(); break;
                    }
                    break;
            }

        }

        // This function is used when StateSmith doesn't know what the active leaf state is at
        // compile time due to sub states or when multiple states need to be exited.
        private void ExitUpToStateHandler(StateId desiredState)
        {
            while (this.CurrentStateId != desiredState)
            {
                switch (this.CurrentStateId)
                {
                    case StateId.CONNECTED: CONNECTED_exit(); break;

                    case StateId.CONNECTEDIDLE: CONNECTEDIDLE_exit(); break;

                    case StateId.SENDING: SENDING_exit(); break;

                    case StateId.CONNECTING: CONNECTING_exit(); break;

                    case StateId.DISCONNECTED: DISCONNECTED_exit(); break;

                    default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
                }
            }
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ROOT
        ////////////////////////////////////////////////////////////////////////////////

        private void ROOT_enter()
        {
            this.CurrentStateId = StateId.ROOT;
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state CONNECTED
        ////////////////////////////////////////////////////////////////////////////////

        private void CONNECTED_enter()
        {
            this.CurrentStateId = StateId.CONNECTED;
        }

        private void CONNECTED_exit()
        {
            this.CurrentStateId = StateId.ROOT;
        }

        private void CONNECTED_disconnect()
        {
            // Connected behavior
            // uml: Disconnect TransitionTo(Disconnected)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Disconnected`.
                DISCONNECTED_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Connected

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state CONNECTEDIDLE
        ////////////////////////////////////////////////////////////////////////////////

        private void CONNECTEDIDLE_enter()
        {
            this.CurrentStateId = StateId.CONNECTEDIDLE;
        }

        private void CONNECTEDIDLE_exit()
        {
            this.CurrentStateId = StateId.CONNECTED;
        }

        private void CONNECTEDIDLE_send()
        {
            // ConnectedIdle behavior
            // uml: Send TransitionTo(Sending)
            {
                // Step 1: Exit states until we reach `Connected` state (Least Common Ancestor for transition).
                CONNECTEDIDLE_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Sending`.
                SENDING_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ConnectedIdle

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state SENDING
        ////////////////////////////////////////////////////////////////////////////////

        private void SENDING_enter()
        {
            this.CurrentStateId = StateId.SENDING;
        }

        private void SENDING_exit()
        {
            this.CurrentStateId = StateId.CONNECTED;
        }

        private void SENDING_finishedsending()
        {
            // Sending behavior
            // uml: FinishedSending TransitionTo(ConnectedIdle)
            {
                // Step 1: Exit states until we reach `Connected` state (Least Common Ancestor for transition).
                SENDING_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ConnectedIdle`.
                CONNECTEDIDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Sending

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state CONNECTING
        ////////////////////////////////////////////////////////////////////////////////

        private void CONNECTING_enter()
        {
            this.CurrentStateId = StateId.CONNECTING;
        }

        private void CONNECTING_exit()
        {
            // Connecting behavior
            // uml: exit / { OnConnectingExit(); }
            {
                // Step 1: execute action `OnConnectingExit();`
                OnConnectingExit();
            } // end of behavior for Connecting

            this.CurrentStateId = StateId.ROOT;
        }

        private void CONNECTING_connected()
        {
            // Connecting behavior
            // uml: Connected TransitionTo(Connected)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                CONNECTING_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Connected`.
                CONNECTED_enter();

                // Connected.<InitialState> behavior
                // uml: TransitionTo(ConnectedIdle)
                {
                    // Step 1: Exit states until we reach `Connected` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `ConnectedIdle`.
                    CONNECTEDIDLE_enter();

                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for Connected.<InitialState>
            } // end of behavior for Connecting

            // No ancestor handles this event.
        }

        private void CONNECTING_connectionfailed()
        {
            // Connecting behavior
            // uml: ConnectionFailed TransitionTo(Disconnected)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                CONNECTING_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Disconnected`.
                DISCONNECTED_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Connecting

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state DISCONNECTED
        ////////////////////////////////////////////////////////////////////////////////

        private void DISCONNECTED_enter()
        {
            this.CurrentStateId = StateId.DISCONNECTED;
        }

        private void DISCONNECTED_exit()
        {
            this.CurrentStateId = StateId.ROOT;
        }

        private void DISCONNECTED_connect()
        {
            // Disconnected behavior
            // uml: Connect / { TryConnectAsync(); } TransitionTo(Connecting)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                DISCONNECTED_exit();

                // Step 2: Transition action: `TryConnectAsync();`.
                TryConnectAsync();

                // Step 3: Enter/move towards transition target `Connecting`.
                CONNECTING_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Disconnected

            // No ancestor handles this event.
        }

        // Thread safe.
        public static string StateIdToString(StateId id)
        {
            switch (id)
            {
                case StateId.ROOT: return "ROOT";
                case StateId.CONNECTED: return "CONNECTED";
                case StateId.CONNECTEDIDLE: return "CONNECTEDIDLE";
                case StateId.SENDING: return "SENDING";
                case StateId.CONNECTING: return "CONNECTING";
                case StateId.DISCONNECTED: return "DISCONNECTED";
                default: return "?";
            }
        }

        // Thread safe.
        public static string EventIdToString(EventId id)
        {
            switch (id)
            {
                case EventId.CONNECT: return "CONNECT";
                case EventId.CONNECTED: return "CONNECTED";
                case EventId.CONNECTIONFAILED: return "CONNECTIONFAILED";
                case EventId.DISCONNECT: return "DISCONNECT";
                case EventId.FINISHEDSENDING: return "FINISHEDSENDING";
                case EventId.SEND: return "SEND";
                default: return "?";
            }
        }
    }
}
